server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fundoo_notes
    username: root
    password: ur pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379